# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: [pylint]
  autoupdate_schedule: monthly

exclude: ^(3rdpart|cmake/ECM|cmake/KDAB/|src/3rdparty/|code.dev.code-workspace)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.4
    hooks:
      - id: clang-format
        exclude: (.json)
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        exclude: ^(.cmake-format.py|conan/conanfile.py)
        # additional_dependencies: ['PySide2', 'PySide6']
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        exclude: ^(.cmake-format.py|conan/.*/conanfile.py)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
        exclude: (cmake/Toolchain-QNX|.py.cmake|.h.cmake|.rc.cmake|Doxyfile.cmake|gammaray.qhcp.cmake)
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
