extends: default

ignore:
  - .cache/
  - .direnv/
  - .flatpak/
  - .flatpak/builder
  - build*/
  - repo/
  - .github/styles/vale/**/*.yml
  - .github/styles/vale/**/*.yaml
rules:
  document-start: disable
  line-length: disable
  quoted-strings:
    required: only-when-needed
    extra-allowed: ['{|}']
    level: warning
  braces:
    max-spaces-inside: 1
  new-lines:
    level: warning
    type: unix
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
